/**
 * Mentorluse olekud on rakenduskihi konstandid (kinnitatud platvormireegel —
 * EI PostgreSQL enum'e). Olekumasinad: ESTA-MENTOR-A0 ptk 4.
 */

export const MENTOR_PROFILE_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  PENDING_REVIEW: "PENDING_REVIEW",
  ACTIVE: "ACTIVE",
  REJECTED: "REJECTED",
  PAUSED: "PAUSED",
  RETIRED: "RETIRED",
  REVOKED: "REVOKED",
  EXTERNAL_REFERENCE: "EXTERNAL_REFERENCE"
});

export const MENTOR_PROFILE_ORIGIN = Object.freeze({
  SELF: "SELF",
  ESTA_IMPORT: "ESTA_IMPORT"
});

export const MENTOR_CONSENT_STATUS = Object.freeze({
  NOT_REQUESTED: "NOT_REQUESTED",
  PENDING_CONSENT: "PENDING_CONSENT",
  CONSENTED: "CONSENTED",
  DECLINED_CONSENT: "DECLINED_CONSENT",
  STALE: "STALE"
});

export const MENTOR_CAPACITY = Object.freeze({
  OPEN: "OPEN",
  FULL: "FULL"
});

export const MENTORING_REQUEST_STATUS = Object.freeze({
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED"
});

export const MENTORING_RELATION_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  CLOSED: "CLOSED"
});

export const MENTORING_MEETING_STATUS = Object.freeze({
  PLANNED: "PLANNED",
  HELD: "HELD",
  CANCELLED: "CANCELLED"
});

export const MENTORING_MEETING_MODE = Object.freeze({
  PLATFORM_ROOM: "PLATFORM_ROOM",
  EXTERNAL: "EXTERNAL"
});

export const MENTORING_SUMMARY_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  PENDING_CONFIRM: "PENDING_CONFIRM",
  CONFIRMED: "CONFIRMED",
  DISCARDED: "DISCARDED"
});

export const MENTORING_SUMMARY_KIND = Object.freeze({
  MEETING: "MEETING",
  MIDTERM: "MIDTERM",
  FINAL: "FINAL"
});

export const MENTORING_NOTE_KIND = Object.freeze({
  NOTE: "NOTE",
  PREPARATION: "PREPARATION"
});

export const MENTORING_CLOSE_REASONS = Object.freeze([
  "completed",
  "not_started",
  "changed_mentor",
  "inactive",
  "account_deleted",
  "other"
]);

// Suhtepõhised positsioonid — MITTE globaalsed rollid (O-EM-4: CLIENT väljas).
export const MENTORING_MEMBER_ROLES = Object.freeze(["SOCIAL_WORKER", "SERVICE_PROVIDER"]);

// Rate-limit ja taimerid (ptk 7.6 + ptk 9).
export const MENTORING_LIMITS = Object.freeze({
  MAX_PENDING_REQUESTS: 5,
  REQUEST_EXPIRY_DAYS: 30,
  DECLINED_COOLDOWN_DAYS: 30,
  DRAFT_RELATION_EXPIRY_DAYS: 30,
  INACTIVITY_CHECK_DAYS: 90,
  INACTIVITY_CLOSE_DAYS: 30,
  MESSAGE_ANONYMIZE_DAYS: 90,
  STALE_EXTERNAL_MONTHS: 12,
  MEETING_UPCOMING_HOURS: 48,
  MAX_TEXT: 4_000,
  MAX_SHORT_TEXT: 600,
  MAX_TAGS: 12,
  MAX_TAG_LENGTH: 120
});

export const MENTORING_AUDIT_ACTIONS = Object.freeze({
  PROFILE_CREATED: "PROFILE_CREATED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  PROFILE_SUBMITTED: "PROFILE_SUBMITTED",
  PROFILE_APPROVED: "PROFILE_APPROVED",
  PROFILE_REJECTED: "PROFILE_REJECTED",
  PROFILE_PAUSED: "PROFILE_PAUSED",
  PROFILE_RESUMED: "PROFILE_RESUMED",
  PROFILE_RETIRED: "PROFILE_RETIRED",
  PROFILE_REVOKED: "PROFILE_REVOKED",
  PROFILE_IMPORTED: "PROFILE_IMPORTED",
  PROFILE_DELETED: "PROFILE_DELETED",
  CONSENT_STATUS_CHANGED: "CONSENT_STATUS_CHANGED",
  REQUEST_CREATED: "REQUEST_CREATED",
  REQUEST_ACCEPTED: "REQUEST_ACCEPTED",
  REQUEST_DECLINED: "REQUEST_DECLINED",
  REQUEST_EXPIRED: "REQUEST_EXPIRED",
  REQUEST_CANCELLED: "REQUEST_CANCELLED",
  REQUEST_ANONYMIZED: "REQUEST_ANONYMIZED",
  RELATION_STARTED: "RELATION_STARTED",
  AGREEMENT_PROPOSED: "AGREEMENT_PROPOSED",
  AGREEMENT_ACCEPTED: "AGREEMENT_ACCEPTED",
  RELATION_ACTIVATED: "RELATION_ACTIVATED",
  RELATION_PAUSED: "RELATION_PAUSED",
  RELATION_RESUMED: "RELATION_RESUMED",
  RELATION_CLOSED: "RELATION_CLOSED",
  RELATION_PURGED: "RELATION_PURGED",
  INACTIVITY_CHECK_SENT: "INACTIVITY_CHECK_SENT",
  MEETING_CREATED: "MEETING_CREATED",
  MEETING_UPDATED: "MEETING_UPDATED",
  MEETING_HELD: "MEETING_HELD",
  MEETING_CANCELLED: "MEETING_CANCELLED",
  SUMMARY_CREATED: "SUMMARY_CREATED",
  SUMMARY_SUBMITTED: "SUMMARY_SUBMITTED",
  SUMMARY_CONFIRMED: "SUMMARY_CONFIRMED",
  SUMMARY_DISCARDED: "SUMMARY_DISCARDED",
  PREPARATION_HANDED_OFF: "PREPARATION_HANDED_OFF",
  PREPARATION_SHARED: "PREPARATION_SHARED",
  PREPARATION_RECALLED: "PREPARATION_RECALLED"
});
