const labels = {
  after_hours_availability: "tööväline kättesaadavus",
  aggression: "agressioon",
  adult_support: "täiskasvanute tugi",
  after_hours: "tööväline kättesaadavus",
  case_notes: "juhtumi märkmed",
  case_discussion: "juhtumiarutelu",
  case_escalation_rule: "juhtumi eskaleerimise reegel",
  case_worker: "juhtumikorraldaja",
  channel_rules: "suhtluskanalite reeglid",
  change_channel: "suhtluskanali muutmine",
  child_protection: "lastekaitse",
  clear: "selge",
  clear_documentation_routine: "selge dokumenteerimisrutiin",
  client_family: "klient või pere",
  client_followup: "kliendi järelkontakt",
  colleague_presence: "kolleegi kaasamine",
  colleague_questions: "kolleegide küsimused",
  complex_family_case: "keeruline perejuhtum",
  critical_incident: "kriitiline juhtum",
  deferrable: "edasilükatav küsimus",
  documentation: "dokumenteerimine",
  documentation_system: "dokumenteerimise või süsteemi katkestus",
  documentation_flow: "dokumenteerimise töövoog",
  document_neutral_facts: "neutraalsed faktid kirja",
  duplicate_entry: "dubleeriv sisestus",
  elderly_support: "eakate tugi",
  email_or_message: "e-kiri või sõnum",
  email: "e-kiri",
  emotional_load: "emotsionaalne koormus",
  emotionally_heavy: "emotsionaalselt raske",
  ended: "ei kesta",
  ethical_tension: "eetiline pinge",
  ethical_tension_case: "eetilise pingega juhtum",
  few: "vähesed",
  first_100_days: "esimesed 100 päeva",
  first_month: "esimene kuu",
  first_week: "esimene nädal",
  focus_time: "fookusaeg",
  general_social_work: "üldine sotsiaaltöö",
  heavy_week: "raske nädal",
  high: "kõrge",
  high_risk_case: "kõrge riskiga juhtum",
  home_visit: "kodukülastus",
  in_72h: "72 tunni pärast",
  information_search: "info otsimine",
  low: "madal",
  many: "palju",
  make_other_agency_decision: "teise asutuse otsuse tegemine",
  manager: "juht",
  manager_check_in: "juhi kontrollpunkt",
  manager_followup: "juhiga järelkontakt",
  manual_copying: "käsitsi ümber kopeerimine",
  manual_status_updates: "käsitsi staatuse uuendamine",
  mentor: "mentor",
  missing_shared_view: "ühise vaate puudumine",
  moderate: "mõõdukas",
  needs_attention: "vajab tähelepanu",
  needs_clarification: "vajab täpsustamist",
  needs_network_discussion: "vajab võrgustiku arutelu",
  negotiable: "kokkulepitav katkestus",
  network_work: "võrgustikutöö",
  new_role: "uus roll samas valdkonnas",
  next_week: "järgmisel nädalal",
  no: "ei",
  no_immediate_danger: "vahetut ohtu ei ole",
  none: "ei ole",
  not_sustainable: "ei ole kestlik",
  not_to_carry_alone: "ei peaks üksi kandma",
  not_yet: "veel kirja panemata",
  office: "kontor või vastuvõtt",
  onboarding_material: "sisseelamismaterjal",
  ongoing: "võib jätkuda",
  partner_agency: "partnerasutus",
  partner: "koostööpartner",
  partner_process: "koostööpartneri protsessi katkestus",
  partial: "osaline",
  partner_channel: "koostööpartneri kanal",
  phone: "telefon",
  prioritize: "vajab prioriseerimist",
  "processes.duplicate_entry": "dubleeriv sisestus tööprotsessis",
  "processes.high_value_loss": "oluline töö jääb madala väärtusega tegevuste taha",
  "processes.single_entry_needed": "vaja üht sisestuskohta",
  "processes.switching_load_high": "töövoogude vahel liikumise koormus on kõrge",
  plan_needed: "plaan vajab täpsustamist",
  process_change: "tööprotsessi muutus",
  public_space: "avalik ruum",
  rare: "harva",
  reduced: "vähenenud",
  repeated_harassment: "korduv ahistav suhtlus",
  repetitive_tasks: "korduvad tegevused",
  repeating_case_pattern: "korduv juhtumimuster",
  risk_escalation: "riskide eskaleerimine",
  role_boundaries: "roll ja vastutus",
  role_boundary: "rollipiir",
  role_expectations: "rolliootuste selgitus",
  role_uncertainty: "rolli ebaselgus",
  same_data_multiple_places: "sama info mitmes kohas",
  searching_partner_info: "partneri info otsimine",
  service_coordination: "teenuste koordineerimine",
  service_rules: "teenuste reeglid",
  shared_status_view: "ühine staatusevaade",
  shadowing: "kogenuma kolleegi jälgimine",
  single_entry: "üks sisestuskoht",
  solve_partner_delay: "partneri viivituse lahendamine",
  some: "mõningane",
  sometimes: "mõnikord",
  soon: "vaja lähiajal kokku leppida",
  stable: "stabiilne",
  "starter_support.mentor_needed": "vaja mentori tuge",
  "starter_support.missing_support": "puuduv tööalane tugi",
  "starter_support.not_to_carry_alone": "olukorda ei peaks üksi kandma",
  supervisor: "supervisioon või muu kokkulepitud tugi",
  team: "tiim",
  team_agreement: "tiimi kokkulepe",
  team_channel: "tiimi kanal",
  today: "täna",
  tomorrow: "homme",
  threat: "ähvardus",
  threatening_message: "ähvardav sõnum või e-kiri",
  unclear: "ebaselge",
  unclear_mandate: "ebaselge mandaadiga juhtum",
  unclear_owner: "vastutaja ebaselge",
  unavoidable: "vältimatu kiire sekkumine",
  urgent_attention: "kiire tähelepanu vajalik",
  urgent: "vaja kiiret kokkulepet",
  very_often: "väga sageli",
  work_arrangement_change: "töökorralduse muutmine",
  work_boundaries: "tööpiirid",
  workplace_violence: "töövägivalla olukord",
  wrong_channel: "vale suhtluskanal",
  yes: "jah",
  green: "roheline",
  yellow: "kollane",
  red: "punane",
  insufficient_data: "andmeid ei ole veel piisavalt",
  manageable: "hallatav",
  support_available: "tugi on olemas",
  organizational_support: "vajab organisatsiooni tuge",
  needs_agreement: "vajab kokkulepet",
  needs_attention: "vajab tähelepanu",
  needs_clearer_support_plan: "vajab selgemat toeplaani",
  needs_clarification: "vajab täpsustamist",
  needs_organizational_change: "vajab töökorralduslikku muutust",
  needs_reorganization: "vajab töö ümberkorraldamist",
  needs_simplification: "vajab lihtsustamist",
  needs_urgent_support_agreement: "vajab kiiret toe kokkulepet",
  needs_workflow_clarification: "vajab töövoo täpsustamist",
  /* Vormide vastusevariandid, millel varem silti ei olnud: valmis tekst trükkis
     siis sisemise väärtuse („reduce next day load"). Sildid on samad, mida inimene
     vormis näeb; tests/wellbeing-display-labels.test.mjs hoiab kaardi täielikuna. */
  critical: "kriitiline",
  routine: "rutiinne",
  complex: "keerukas",
  very_complex: "väga keerukas",
  very_high: "väga kõrge",
  sufficient: "piisav",
  partly_clear: "osaliselt selge",
  available: "kättesaadav",
  not_available: "pole kättesaadav",
  ethical_dilemma: "eetiline dilemma",
  complex_case: "töökorralduslikult keeruline",
  trauma_related: "traumaga kokkupuude",
  role_conflict: "rollikonflikt",
  uncertain: "pole kindel",
  social_worker: "sotsiaaltöötaja",
  advisor: "nõustaja",
  coordinator: "koordinaator",
  moral_distress: "moraalne stress",
  trauma_exposure: "traumaga kokkupuude",
  workload_followup: "järeltegevuste töömaht",
  strong: "tugev",
  indirect: "kaudne",
  direct: "otsene",
  document_key_facts: "tööks vajalikud faktid kirja",
  reduce_next_day_load: "järgmise päeva koormuse vähendamine",
  colleague_debrief: "kolleegiga tööalane järelarutelu",
  safety_followup: "ohutuse järelkontroll",
  covision_input: "kovisiooni sisendi ettevalmistus",
  insult_or_humiliation: "solvamine või alandamine",
  physical_danger: "füüsiline oht",
  stalking_or_intimidation: "jälitamine või hirmutamine",
  lone_work_risk: "kodukülastuse või üksi töötamise risk",
  difficult_case: "raske juhtum",
  long_overload: "pikaajaline ülekoormus",
  interruptions: "katkestused",
  colleague: "kolleeg",
  work_time_boundary: "tööaja piir",
  evening_messages: "õhtuste sõnumite kokkulepe",
  pause_agreement: "pauside kaitsmine",
  replacement_agreement: "asenduse kokkulepe",
  crisis_exception: "kriisiolukorra erandid",
  urgent_requests: "kiirete päringute piir",
  protected: "kaitstud",
  missing: "puudub",
  one_week: "ühe nädala pärast",
  two_weeks: "kahe nädala pärast",
  one_month: "kuu aja pärast",
  next_meeting: "järgmisel kohtumisel",
  message: "sõnum",
  manager_requests: "juhi päringud",
  client_contact: "kliendikontakt",
  partner_contact: "koostööpartner",
  meetings: "koosolekud",
  urgent_cases: "kiired juhtumid",
  often: "sageli",
  case_flow: "juhtumitöö töövoog",
  partner_coordination: "partneritega kooskõlastamine",
  team_routine: "tiimi korduv rutiin",
  information_flow: "info liikumine",
  client_value_work: "väärtust loov klienditöö",
  necessary_burden: "vajalik, kuid koormav töö",
  waiting: "ootamine",
  low_value_work: "vähese väärtusega tegevused",
  waiting_for_answers: "vastuste ootamine",
  copying_between_systems: "süsteemide vahel kopeerimine",
  unclear_next_step: "ebaselge järgmine samm",
  status_chasing: "seisu tagaajamine",
  duplicate_meetings: "dubleerivad arutelud",
  unclear_templates: "ebaselged mallid",
  partner_delay: "partneri viivitus",
  system_gap: "süsteemide vahe",
  role_confusion: "rollisegadus",
  partner_reply: "partnerile vastamine",
  planning: "planeerimine",
  recovery_pause: "paus või taastumine",
  clear_owner: "selge omanik",
  template_cleanup: "malli korrastus",
  meeting_rule: "koosolekureegel",
  client: "klient",
  network: "võrgustik",
  explain_service: "teenuse või otsuse selgitus",
  be_always_available: "pidev kättesaadavus",
  make_decision: "otsuse tegemine",
  coordinate_network: "võrgustiku koordineerimine",
  emotional_support: "emotsionaalne tugi",
  service_link: "teenuse või kontakti vahendamine",
  assessment_input: "hindamise sisendi kogumine",
  support_planning: "toe planeerimine",
  replace_service_provider: "teenuseosutaja rolli asendamine",
  be_crisis_contact: "kriisikontakti roll",
  guarantee_outcome: "tulemuse garanteerimine",
  carry_partner_responsibility: "partneri vastutuse kandmine",
  self: "minu rolli piires lahendatav",
  service_provider: "teenuseosutaja panus",
  disability_support: "puuetega inimeste tugi",
  covision: "kovisioon",
  boundary_agreement: "tööpiiride kokkulepe",
  /* Arvutatud märked (koormus- ja ressursitegurid, riskimärgid): varem trükiti need
     toe mustandisse ja kovisiooni sisendisse sisemise koodina. */
  "ethical_tension.elevated": "kõrgenenud eetiline pinge",
  "moral_distress.present": "moraalne stress",
  "trauma.exposure": "kokkupuude traumaga",
  "support.do_not_carry_alone": "juhtumit ei peaks üksi kandma",
  "role.clarity_partial_or_unclear": "roll või vastutus ei ole päris selge",
  "recovery.follow_up_needed": "taastumine vajab plaani või tuge",
  "hard_case.immediate_danger": "vahetu oht võib jätkuda",
  "hard_case.immediate_danger_uncertain": "vahetu ohu kohta ei ole kindlust",
  "hard_case.should_not_carry_alone": "juhtumit ei peaks üksi kandma",
  "hard_case.direct_trauma_exposure": "otsene kokkupuude traumaga",
  "hard_case.high_ethical_tension": "kõrge eetiline pinge",
  "interruptions.high_frequency": "katkestusi on sageli",
  "interruptions.work_impact": "katkestused mõjutavad tööd",
  "interruptions.wrong_channel": "katkestused tulevad valest kanalist",
  "interruptions.documentation_system": "dokumenteerimine või süsteem katkestab töövoogu",
  "interruptions.role_boundary": "katkestused ületavad rollipiiri",
  "interruptions.partner_process": "katkestused tulevad koostööpartneri protsessist",
  "focus_time.agreement_needed": "vaja on fookusaja kokkulepet",
  "channels.agreement_needed": "vaja on suhtluskanalite kokkulepet",
  "urgency.criteria_unclear": "ei ole selge, millal tuleb kohe reageerida",
  "process.documentation_simplification_needed": "dokumenteerimine vajab lihtsustamist",
  "interruptions.recovery_impact_high": "katkestused mõjutavad tugevalt taastumist",
  "interruptions.very_frequent": "katkestusi on väga sageli",
  "interruptions.many_can_wait": "paljud katkestused saaksid oodata",
  "recovery.low_capacity_72h": "töövõime on järgmise 72 tunni vaates madal",
  "recovery.no_recovery_with_low_capacity": "taastumisvõimalus puudub ja töövõime on madal",
  "role_boundaries.role_conflict_high": "kõrge rollikonflikt",
  "role_boundaries.role_conflict_moderate": "mõõdukas rollikonflikt",
  "role_boundaries.partner_explanation_needed": "partner vajab rolliselgitust",
  "role_boundaries.availability_pressure_high": "tugev surve olla pidevalt kättesaadav",
  "role_boundaries.ethical_complexity_high": "kõrge eetiline keerukus",
  "role_boundaries.manager_discussion_needed": "vaja on arutelu juhiga",
  "role_boundaries.partner_clarification_needed": "vaja on selgitust koostööpartnerile",
  "role_boundaries.shared_responsibility_needed": "vastutus vajab jagamist",
  "role_boundaries.responsibility_shift": "oodatakse seda, mis ei ole minu roll",
  "role_boundaries.partner_responsibility_gap": "vaja on koostööpartneri panust",
  "role_boundaries.ethical_tension": "rollipiiriga seotud eetiline pinge",
  "starter_support.cases_not_carry_alone": "juhtumid, mida ei peaks üksi kandma",
  "starter_support.role_uncertainty": "roll ja vastutus on ebaselged",
  "starter_support.documentation_uncertainty": "dokumenteerimine on ebaselge",
  "starter_support.manager_check_needed": "vaja on arutelu juhiga",
  "starter_support.boundary_plan_needed": "vaja on tööpiiride kokkulepet",
  "starter_support.covision_needed": "vaja on kovisiooni",
  "starter_support.early_role_uncertainty": "rolli ebaselgus töö alguses",
  "starter_support.support_agreement_needed_soon": "toe kokkulepet on vaja peagi",
  "support.replacement_unclear": "asendus või info liikumine on ebaselge",
  "boundaries.after_hours_unclear": "töövälise kättesaadavuse piir on ebaselge",
  "boundaries.no_pause_protection": "pausid ei ole kaitstud",
  "work_impact.elevated": "mõju tööle on kõrgenenud",
  "safety_impact.present": "mõju turvatundele",
  "documentation.needs_neutral_record": "juhtum vajab neutraalset kirjapanekut",
  "safety.agreement_needed": "vaja on turvalisuse kokkulepet",
  "workplace_violence.danger_ongoing": "oht võib jätkuda",
  "workplace_violence.danger_uncertain": "ohu kestmise kohta ei ole kindlust",
  "workplace_violence.physical_danger": "füüsiline oht",
  "workplace_violence.threat": "ähvardus",
  "workplace_violence.safety_impact_high": "tugev mõju turvatundele",
  "processes.documentation_load": "dokumenteerimise koormus",
  "processes.information_search": "info otsimine",
  "processes.waiting": "ootamine",
  "processes.repetitive_tasks": "korduvad tegevused",
  "processes.shared_status_view_needed": "vaja on ühist seisuvaadet",
  "processes.owner_clarity_needed": "vaja on selget vastutajat",
  "processes.information_flow_needed": "vaja on ühist vaadet infole",
  "processes.duplicate_documentation_high": "dubleerivat dokumenteerimist on palju",
  "processes.unfinished_work_accumulates": "lõpetamata töö kuhjub",
  "risk.workplace_violence": "märgitud on töövägivalla kogemus",
  "support.manager": "vaja on kokkulepet juhiga",
  "support.colleague": "vaja on kolleegi tuge",
  "support.supervisor": "vaja on supervisiooni või muud kokkulepitud tuge",
  /* Kiirkontrolli arvutatud tegurid. Samad laused (väikese algustähega, sest silte liidetakse ka lausesse) mis `lib/wellbeing/quickCheck.js`
     `factorLabels`-is: ilma täpse sildita annaks võtme lõpp („high") ainult
     „kõrge" ja kirjete lehel ei oleks näha, MIS on kõrge. Test hoiab kaks
     loendit võrdsena. */
  "workload.high": "töömaht on kõrge",
  "case_complexity.high": "juhtumite keerukus on kõrge",
  "emotional_load.high": "emotsionaalne koormus on kõrge",
  "documentation.high": "dokumenteerimise koormus on kõrge",
  "interruptions.high": "katkestuste tase on kõrge",
  "after_hours.impact": "töövälise kättesaadavuse mõju on kõrge",
  "recovery.low_or_none": "taastumisvõimalus on vähene või puudub",
  "support.unclear_or_missing": "juhi või kolleegi tugi on ebaselge või puudub",
  "decision_control.low": "otsustusruum töö üle on vähene",
  "clarity.unclear": "prioriteedid või tööpiirid on ebaselged",
  "risk.difficult_case": "märgitud on raske juhtum",
  "recovery.none_with_critical_workload": "kriitiline töömaht koos puuduva taastumisega"
};

/* Liitkood (nt „hard_case.load.emotional_load", „violence.threat"): arvutus paneb
   välja väärtuse ette oma ala. Silt tuleb siis väärtusest endast ehk koodi
   viimasest osast. */
function labelFor(value) {
  const normalized = String(value || "").trim();
  if (!normalized) return "";
  if (Object.prototype.hasOwnProperty.call(labels, normalized)) return labels[normalized];
  const tail = normalized.slice(normalized.lastIndexOf(".") + 1);
  return tail !== normalized && Object.prototype.hasOwnProperty.call(labels, tail) ? labels[tail] : "";
}

/** Kas väärtusel on TÄPNE silt (mitte võtme lõpu järgi leitud)? Arvutatud
 *  tegur vajab täpset silti: „workload.high" lõpp annaks ainult „kõrge". */
export function wellbeingHasExactLabel(value) {
  return Object.prototype.hasOwnProperty.call(labels, String(value || "").trim());
}

/** Kas väärtusel on päris silt? Ilma sildita trükiks tekst sisemise väärtuse. */
export function wellbeingHasLabel(value) {
  return Boolean(labelFor(value));
}

export function wellbeingLabel(value, fallback = "täpsustamisel") {
  const normalized = String(value || "").trim();
  if (!normalized) return fallback;
  return labelFor(normalized) || normalized.replaceAll("_", " ");
}

export function wellbeingLabelList(values = [], fallback = "täpsustada") {
  const items = Array.isArray(values) ? values.filter(Boolean) : [];
  if (!items.length) return [`- ${fallback}`];
  return items.map((item) => `- ${wellbeingLabel(item)}`);
}

export function wellbeingInlineList(values = [], fallback = "täpsustamisel") {
  const items = Array.isArray(values) ? values.filter(Boolean) : [];
  if (!items.length) return fallback;
  return items.map((item) => wellbeingLabel(item)).join(", ");
}
