const labels = {
  after_hours_availability: "tööväline kättesaadavus",
  aggression: "agressioon",
  adult_support: "täiskasvanute tugi",
  after_hours: "tööväline kättesaadavus",
  case_notes: "juhtumi märkmed",
  case_discussion: "juhtumiarutelu",
  case_escalation_rule: "juhtumi eskaleerimise reegel",
  case_worker: "juhtumikorraldaja",
  channel_rules: "suhtluskanalite reeglid",
  change_channel: "suhtluskanali muutmine",
  child_protection: "lastekaitse",
  clear: "selge",
  clear_documentation_routine: "selge dokumenteerimisrutiin",
  client_family: "klient või pere",
  client_followup: "kliendi järelkontakt",
  colleague_presence: "kolleegi kaasamine",
  colleague_questions: "kolleegide küsimused",
  complex_family_case: "keeruline perejuhtum",
  critical_incident: "kriitiline juhtum",
  deferrable: "edasilükatav küsimus",
  documentation: "dokumenteerimine",
  documentation_system: "dokumenteerimise või süsteemi katkestus",
  documentation_flow: "dokumenteerimise töövoog",
  document_neutral_facts: "neutraalsed faktid kirja",
  duplicate_entry: "dubleeriv sisestus",
  elderly_support: "eakate tugi",
  email_or_message: "e-kiri või sõnum",
  email: "e-kiri",
  emotional_load: "emotsionaalne koormus",
  emotionally_heavy: "emotsionaalselt raske",
  ended: "ei kesta",
  ethical_tension: "eetiline pinge",
  ethical_tension_case: "eetilise pingega juhtum",
  few: "vähesed",
  first_100_days: "esimesed 100 päeva",
  first_month: "esimene kuu",
  first_week: "esimene nädal",
  focus_time: "fookusaeg",
  general_social_work: "üldine sotsiaaltöö",
  heavy_week: "raske nädal",
  high: "kõrge",
  high_risk_case: "kõrge riskiga juhtum",
  home_visit: "kodukülastus",
  in_72h: "72 tunni pärast",
  information_search: "info otsimine",
  low: "madal",
  many: "palju",
  make_other_agency_decision: "teise asutuse otsuse tegemine",
  manager: "juht",
  manager_check_in: "juhi kontrollpunkt",
  manager_followup: "juhiga järelkontakt",
  manual_copying: "käsitsi ümber kopeerimine",
  manual_status_updates: "käsitsi staatuse uuendamine",
  mentor: "mentor",
  missing_shared_view: "ühise vaate puudumine",
  moderate: "mõõdukas",
  needs_attention: "vajab tähelepanu",
  needs_clarification: "vajab täpsustamist",
  needs_network_discussion: "vajab võrgustiku arutelu",
  negotiable: "kokkulepitav katkestus",
  network_work: "võrgustikutöö",
  new_role: "uus roll samas valdkonnas",
  next_week: "järgmisel nädalal",
  no: "ei",
  no_immediate_danger: "vahetut ohtu ei ole",
  none: "ei ole",
  not_sustainable: "ei ole kestlik",
  not_to_carry_alone: "ei peaks üksi kandma",
  not_yet: "veel kirja panemata",
  office: "kontor või vastuvõtt",
  onboarding_material: "sisseelamismaterjal",
  ongoing: "võib jätkuda",
  partner_agency: "partnerasutus",
  partner: "koostööpartner",
  partner_process: "koostööpartneri protsessi katkestus",
  partial: "osaline",
  partner_channel: "koostööpartneri kanal",
  phone: "telefon",
  plan_needed: "plaan vajab täpsustamist",
  process_change: "tööprotsessi muutus",
  public_space: "avalik ruum",
  rare: "harva",
  reduced: "vähenenud",
  repeated_harassment: "korduv ahistav suhtlus",
  repetitive_tasks: "korduvad tegevused",
  repeating_case_pattern: "korduv juhtumimuster",
  risk_escalation: "riskide eskaleerimine",
  role_boundaries: "roll ja vastutus",
  role_boundary: "rollipiir",
  role_expectations: "rolliootuste selgitus",
  role_uncertainty: "rolli ebaselgus",
  same_data_multiple_places: "sama info mitmes kohas",
  searching_partner_info: "partneri info otsimine",
  service_coordination: "teenuste koordineerimine",
  service_rules: "teenuste reeglid",
  shared_status_view: "ühine staatusevaade",
  shadowing: "kogenuma kolleegi jälgimine",
  single_entry: "üks sisestuskoht",
  solve_partner_delay: "partneri viivituse lahendamine",
  some: "mõningane",
  sometimes: "mõnikord",
  soon: "vaja lähiajal kokku leppida",
  stable: "stabiilne",
  supervisor: "supervisioon või muu kokkulepitud tugi",
  team: "tiim",
  team_agreement: "tiimi kokkulepe",
  team_channel: "tiimi kanal",
  today: "täna",
  tomorrow: "homme",
  threat: "ähvardus",
  threatening_message: "ähvardav sõnum või e-kiri",
  unclear: "ebaselge",
  unclear_mandate: "ebaselge mandaadiga juhtum",
  unclear_owner: "vastutaja ebaselge",
  unavoidable: "vältimatu kiire sekkumine",
  urgent_attention: "kiire tähelepanu vajalik",
  urgent: "vaja kiiret kokkulepet",
  very_often: "väga sageli",
  work_arrangement_change: "töökorralduse muutmine",
  work_boundaries: "tööpiirid",
  workplace_violence: "töövägivalla olukord",
  wrong_channel: "vale suhtluskanal",
  yes: "jah"
};

export function wellbeingLabel(value, fallback = "täpsustamisel") {
  const normalized = String(value || "").trim();
  if (!normalized) return fallback;
  return labels[normalized] || normalized.replaceAll("_", " ");
}

export function wellbeingLabelList(values = [], fallback = "täpsustada") {
  const items = Array.isArray(values) ? values.filter(Boolean) : [];
  if (!items.length) return [`- ${fallback}`];
  return items.map((item) => `- ${wellbeingLabel(item)}`);
}

export function wellbeingInlineList(values = [], fallback = "täpsustamisel") {
  const items = Array.isArray(values) ? values.filter(Boolean) : [];
  if (!items.length) return fallback;
  return items.map((item) => wellbeingLabel(item)).join(", ");
}
