[Unit]
BindsTo=var-lib-sotsiaalai-materials.mount
Requires=var-lib-sotsiaalai-materials.mount
After=var-lib-sotsiaalai-materials.mount

[Service]
ExecStartPre=/usr/local/bin/sotsiaalai-materials-storage-verify
