import test from "node:test"
import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"

import { deleteOwnedArtifactWithAudit } from "../../lib/documents/artifactDeletion.js"
import { writeDocumentAudit } from "../../lib/documents/audit.js"

function deletionDb({ auditFails = false } = {}) {
  const state = { exists: true, audits: 0 }
  const tx = {
    agentArtifact: {
      deleteMany: async () => {
        if (!state.exists) return { count: 0 }
        state.exists = false
        return { count: 1 }
      }
    },
    documentAudit: {
      create: async () => {
        if (auditFails) throw new Error("INJECTED_DOCUMENT_AUDIT_FAILURE")
        state.audits += 1
        return {}
      }
    }
  }
  return {
    state,
    $transaction: async (run) => {
      const before = { ...state }
      try {
        return await run(tx)
      } catch (error) {
        Object.assign(state, before)
        throw error
      }
    }
  }
}

test("SOL-DOC-J-06: artifact audit failure rolls deletion back", async () => {
  const db = deletionDb({ auditFails: true })
  await assert.rejects(
    () => deleteOwnedArtifactWithAudit(
      { artifact: { id: "artifact_1", title: "A", status: "FINAL" }, ownerId: "owner_1" },
      { db }
    ),
    /INJECTED_DOCUMENT_AUDIT_FAILURE/
  )
  assert.equal(db.state.exists, true)
  assert.equal(db.state.audits, 0)
})

test("SOL-DOC-J-06: successful artifact deletion writes exactly one audit", async () => {
  const db = deletionDb()
  await deleteOwnedArtifactWithAudit(
    { artifact: { id: "artifact_1", title: "A", status: "FINAL" }, ownerId: "owner_1" },
    { db }
  )
  assert.equal(db.state.exists, false)
  assert.equal(db.state.audits, 1)
})

test("SOL-DOC-J-06: both download routes audit after bytes exist and before Response", async () => {
  const routes = await Promise.all([
    readFile(new URL("../../app/api/documents/[id]/download/route.js", import.meta.url), "utf8"),
    readFile(new URL("../../app/api/documents/artifacts/[id]/download/route.js", import.meta.url), "utf8")
  ])
  for (const source of routes) {
    const bytes = source.indexOf("fileBuffer")
    const audit = source.indexOf("await writeDocumentAudit(")
    const response = source.indexOf("return new Response(")
    assert.ok(bytes >= 0 && bytes < audit)
    assert.ok(audit >= 0 && audit < response)
    assert.doesNotMatch(source, /logDocumentsAudit\([^)]*downloaded/)
  }
})

for (const [event, identity] of [
  ["document.downloaded", { documentId: "document_1" }],
  ["artifact.downloaded", { artifactId: "artifact_1" }]
]) {
  test(`SOL-DOC-J-06: ${event} audit failure propagates after generation`, async () => {
    const generatedFile = Buffer.from("already generated bytes")
    assert.ok(generatedFile.byteLength > 0)
    await assert.rejects(
      () => writeDocumentAudit(
        event,
        { userId: "owner_1", ...identity },
        { db: { documentAudit: { create: async () => { throw new Error("INJECTED_DOWNLOAD_AUDIT_FAILURE") } } } }
      ),
      /INJECTED_DOWNLOAD_AUDIT_FAILURE/
    )
  })
}
